/*
 * Carbon Discoveries fact pool.
 *
 * Every statistic here is sourced from a named report/agency page
 * verified at write time - no fabricated numbers or URLs.
 */

export type CarbonFact = {
  id: string;
  category: string;
  icon: string;
  title: string;
  fact: string;
  sourceName: string;
  sourceUrl: string;
};

export const CARBON_FACTS: CarbonFact[] = [
  {
    id: "fact_001",
    category: "transport",
    icon: "car",
    title: "Did you know?",
    fact: "Road vehicles — cars, trucks, and buses — produce roughly three-quarters of all transport-sector CO₂, more than aviation and shipping combined.",
    sourceName: "Our World in Data",
    sourceUrl: "https://ourworldindata.org/co2-emissions-from-transport",
  },
  {
    id: "fact_002",
    category: "flights",
    icon: "plane",
    title: "Did you know?",
    fact: "Aviation makes up only about 2.5% of global CO₂ emissions, yet a single long-haul flight can outweigh months of an average person's everyday footprint.",
    sourceName: "IEA",
    sourceUrl: "https://www.iea.org/reports/aviation-and-shipping",
  },
  {
    id: "fact_003",
    category: "cars",
    icon: "car",
    title: "Did you know?",
    fact: "Even after accounting for battery manufacturing, a typical electric car's lifetime emissions are already about half those of an equivalent gasoline car.",
    sourceName: "IEA Global EV Outlook 2024",
    sourceUrl: "https://www.iea.org/reports/global-ev-outlook-2024/outlook-for-emissions-reductions",
  },
  {
    id: "fact_004",
    category: "public transport",
    icon: "bus",
    title: "Did you know?",
    fact: "Shifting a daily commute from car to bus or train is one of the few individual choices researchers rank as genuinely high-impact for cutting emissions.",
    sourceName: "Our World in Data",
    sourceUrl: "https://ourworldindata.org/co2-emissions-from-transport",
  },
  {
    id: "fact_005",
    category: "electricity",
    icon: "zap",
    title: "Did you know?",
    fact: "In 2024, 91% of newly built renewable power projects worldwide were already cheaper than any fossil-fuel alternative.",
    sourceName: "IRENA",
    sourceUrl: "https://www.irena.org/-/media/Files/IRENA/Agency/Publication/2025/Jul/IRENA_TEC_RPGC_in_2024_Summary_2025.pdf",
  },
  {
    id: "fact_006",
    category: "renewable energy",
    icon: "sun",
    title: "Did you know?",
    fact: "New solar power is now about 41% cheaper, and onshore wind about 53% cheaper, than the lowest-cost fossil fuel option.",
    sourceName: "IRENA",
    sourceUrl: "https://www.irena.org/-/media/Files/IRENA/Agency/Publication/2025/Jul/IRENA_TEC_RPGC_in_2024_Summary_2025.pdf",
  },
  {
    id: "fact_007",
    category: "food",
    icon: "utensils",
    title: "Did you know?",
    fact: "Food production causes roughly a quarter of global greenhouse gas emissions — more than every car, ship, train, and plane on Earth combined.",
    sourceName: "Our World in Data",
    sourceUrl: "https://ourworldindata.org/food-ghg-emissions",
  },
  {
    id: "fact_008",
    category: "food",
    icon: "utensils",
    title: "Did you know?",
    fact: "Getting 100g of protein from beef emits about 25kg of CO₂-equivalent on average — roughly 90 times more than the same protein from peas.",
    sourceName: "Our World in Data",
    sourceUrl: "https://ourworldindata.org/carbon-footprint-food-methane",
  },
  {
    id: "fact_009",
    category: "food waste",
    icon: "trash",
    title: "Did you know?",
    fact: "Households, retailers, and food services wasted over a billion meals a day in 2022 — about a fifth of all food that reaches them.",
    sourceName: "UNEP Food Waste Index Report 2024",
    sourceUrl: "https://www.unep.org/resources/publication/food-waste-index-report-2024",
  },
  {
    id: "fact_010",
    category: "agriculture",
    icon: "sprout",
    title: "Did you know?",
    fact: "Livestock supply chains — feed, digestion, and manure — account for about 14.5% of all human-caused greenhouse gas emissions.",
    sourceName: "FAO",
    sourceUrl: "https://www.fao.org/newsroom/detail/new-fao-report-maps-pathways-towards-lower-livestock-emissions/en",
  },
  {
    id: "fact_011",
    category: "forests",
    icon: "trees",
    title: "Did you know?",
    fact: "Tropical deforestation alone releases about 2.6 billion tonnes of CO₂ every year, even before counting the carbon those forests would have absorbed.",
    sourceName: "Our World in Data",
    sourceUrl: "https://ourworldindata.org/deforestation",
  },
  {
    id: "fact_012",
    category: "oceans",
    icon: "waves",
    title: "Did you know?",
    fact: "The ocean absorbs roughly a quarter of the CO₂ we emit each year — and has become about 30% more acidic since the industrial revolution as a result.",
    sourceName: "NOAA",
    sourceUrl: "https://www.noaa.gov/education/resource-collections/ocean-coasts/ocean-acidification",
  },
  {
    id: "fact_013",
    category: "cement",
    icon: "factory",
    title: "Did you know?",
    fact: "Cement production released 2.4 billion tonnes of CO₂ in 2023 alone — about 6.5% of global emissions from a single industrial material.",
    sourceName: "IEA",
    sourceUrl: "https://www.iea.org/energy-system/industry/cement",
  },
  {
    id: "fact_014",
    category: "manufacturing",
    icon: "factory",
    title: "Did you know?",
    fact: "Making steel accounts for roughly 7–8% of the entire world's energy-system CO₂ emissions — more than aviation and shipping combined.",
    sourceName: "IEA",
    sourceUrl: "https://www.iea.org/energy-system/industry/steel",
  },
  {
    id: "fact_015",
    category: "plastic",
    icon: "package",
    title: "Did you know?",
    fact: "Global plastic production has grown more than 200-fold since 1950, and the world now makes over 450 million tonnes a year — most of it from fossil fuels.",
    sourceName: "Our World in Data",
    sourceUrl: "https://ourworldindata.org/plastic-pollution",
  },
  {
    id: "fact_016",
    category: "waste",
    icon: "recycle",
    title: "Did you know?",
    fact: "Recycling aluminum uses about 95% less energy than producing it from raw ore — one recycled can saves enough energy to run a TV for three hours.",
    sourceName: "EPA",
    sourceUrl: "https://www.epa.gov/facts-and-figures-about-materials-waste-and-recycling/aluminum-material-specific-data",
  },
  {
    id: "fact_017",
    category: "waste",
    icon: "trash",
    title: "Did you know?",
    fact: "Landfills are one of the largest human sources of methane — in the US alone, a single year of landfill gas rivals the emissions of 24 million cars.",
    sourceName: "EPA",
    sourceUrl: "https://www.epa.gov/lmop/basic-information-about-landfill-gas",
  },
  {
    id: "fact_018",
    category: "greenhouse gases",
    icon: "cloud",
    title: "Did you know?",
    fact: "Methane traps over 28 times more heat than CO₂ over a 100-year period, which is why cutting it can slow warming unusually fast despite its smaller share.",
    sourceName: "EPA",
    sourceUrl: "https://www.epa.gov/ghgemissions/understanding-global-warming-potentials",
  },
  {
    id: "fact_019",
    category: "everyday activities",
    icon: "footprints",
    title: "Did you know?",
    fact: "Home energy, transportation, and waste are the three levers that decide most of a household's carbon footprint — exactly what footprint calculators measure.",
    sourceName: "EPA Household Carbon Footprint Calculator",
    sourceUrl: "https://www.epa.gov/ghgemissions/carbon-footprint-calculator",
  },
  {
    id: "fact_020",
    category: "carbon cycle",
    icon: "globe",
    title: "Did you know?",
    fact: "Forests and oceans together absorb roughly half of all human CO₂ emissions each year — but that natural sink has grown about 15% weaker under climate change.",
    sourceName: "Carbon Brief",
    sourceUrl: "https://www.carbonbrief.org/analysis-fossil-fuel-co2-emissions-to-set-new-record-in-2025-as-land-sink-recovers",
  },
  {
    id: "fact_021",
    category: "food",
    icon: "utensils",
    title: "Did you know?",
    fact: "Switching to less meat almost always beats switching to 'sustainably farmed' meat when it comes to shrinking a diet's carbon footprint.",
    sourceName: "Our World in Data",
    sourceUrl: "https://ourworldindata.org/less-meat-or-sustainable-meat",
  },
  {
    id: "fact_022",
    category: "cars",
    icon: "car",
    title: "Did you know?",
    fact: "A typical gasoline car emits about 4.6 tonnes of CO₂ a year — more than an average person's entire annual footprint in many countries.",
    sourceName: "EPA",
    sourceUrl: "https://www.epa.gov/greenvehicles/greenhouse-gas-emissions-typical-passenger-vehicle",
  },
];
